include common.mk

$(FNAME_FULL_OBJ): LOCAL_CXXFLAGS := $(LOCAL_CXXFLAGS)
$(FNAME_FULL_OBJ): LOCAL_LDFLAGS := $(LOCAL_LDFLAGS)
$(FNAME_FULL_OBJ): INCLUDES := $(INCLUDES)
$(FNAME_FULL_OBJ): OBJS_FULL := $(OBJS_FULL)
$(FNAME_FULL_OBJ): $(OBJS_FULL) $(LIBS_DEPEND)
	$(CXX) $(OBJS_FULL) $(LOCAL_CXXFLAGS) $(LOCAL_LDFLAGS) $(INCLUDES) -o $@

$(FNAME_FULL_BIN): $(FNAME_FULL_OBJ) | $(BINDIR)
	$(CP) $< $@
	
$(OUT_NAME):  $(FNAME_FULL_BIN)